version: '3'
services:
    laravel-app:
        container_name: laravel-app
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - laravel-mysql
    laravel-mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
